In [32]:
#Importar librerias necesarias
import pandas as pd

In [33]:
#Carga desde un archivo .csv sin indice
ventas_totales = pd.read_csv("Ventas_totales.csv")
ventas_totales

,indice_tiempo,ventas_precios_corrientes,ventas_precios_constantes,ventas_totales_canal_venta,salon_ventas,canales_on_line,ventas_totales_medio_pago,efectivo,tarjetas_debito,tarjetas_credito,...,almacen,panaderia,lacteos,carnes,verduleria_fruteria,alimentos_preparados_rotiseria,articulos_limpieza_perfumeria,indumentaria_calzado_textiles_hogar,electronicos_articulos_hogar,otros
0,01/01/2017,27858.9,27477.3,2.785887e+07,2.759173e+07,2.671420e+05,2.785887e+07,1.023010e+07,6.864575e+06,9.047205e+06,...,6.705475e+06,9.459063e+05,2.880656e+06,2.606193e+06,1.050314e+06,3.407774e+05,4.397544e+06,7.723718e+05,1.838507e+06,2.806660e+06
1,01/02/2017,25994.2,25223.4,2.599420e+07,2.574918e+07,2.450208e+05,2.599420e+07,9.719067e+06,6.438494e+06,8.309150e+06,...,6.576625e+06,9.256186e+05,2.855640e+06,2.600084e+06,1.026167e+06,3.282887e+05,4.053284e+06,6.722905e+05,1.257662e+06,2.354085e+06
2,01/03/2017,27780.0,26334.3,2.778001e+07,2.747223e+07,3.077778e+05,2.778001e+07,1.024444e+07,6.908523e+06,8.845010e+06,...,7.437264e+06,1.016148e+06,3.188259e+06,2.824977e+06,1.075526e+06,3.533352e+05,4.354198e+06,6.676967e+05,1.305675e+06,2.266189e+06
3,01/04/2017,29134.3,27045.9,2.913427e+07,2.882748e+07,3.067927e+05,2.913427e+07,1.031263e+07,7.454252e+06,9.458167e+06,...,8.211244e+06,1.132396e+06,3.257140e+06,3.006159e+06,1.037213e+06,3.596945e+05,4.355707e+06,8.389482e+05,1.535726e+06,2.146756e+06
4,01/05/2017,27969.0,25631.9,2.796900e+07,2.756931e+07,3.996933e+05,2.796900e+07,1.014761e+07,6.735747e+06,9.220930e+06,...,7.651058e+06,1.033082e+06,3.232636e+06,2.799142e+06,9.826512e+05,3.365680e+05,4.206102e+06,9.158951e+05,1.824462e+06,2.117971e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,01/01/2022,154517.1,45463.4,1.545171e+08,1.496976e+08,4.819480e+06,1.545171e+08,4.696260e+07,4.605365e+07,5.404833e+07,...,3.750517e+07,4.860318e+06,1.610477e+07,1.740849e+07,6.138441e+06,1.401929e+06,2.133021e+07,3.782646e+06,1.218755e+07,1.343307e+07
61,01/02/2022,152202.6,23802.1,1.522026e+08,1.484065e+08,3.796044e+06,1.522026e+08,4.629096e+07,4.528358e+07,5.370589e+07,...,3.820979e+07,5.045920e+06,1.613982e+07,1.826074e+07,6.436028e+06,1.370640e+06,2.030545e+07,NaN,9.189746e+06,1.330139e+07
62,01/03/2022,16.5,24612.4,1.689825e+08,1.643211e+08,4.661350e+05,1.689825e+08,5.126208e+07,4.736436e+07,NaN,...,4.541886e+07,5.922820e+06,1.841916e+07,2.082760e+07,6.886240e+06,1.589119e+06,2.294201e+07,3.912852e+06,1.089879e+07,NaN
63,01/04/2022,177148.1,24140.5,1.771481e+08,1.730038e+08,4.144284e+06,1.771481e+08,5.319000e+07,5.006397e+07,6.535759e+07,...,4.999168e+07,6.746167e+06,1.930946e+07,2.287784e+07,6.510666e+06,1.719459e+06,2.313127e+07,4.228054e+06,NaN,1.191048e+07
64,01/05/2022,179639.2,23234.2,1.796392e+08,1.753585e+08,4.280751e+06,1.796392e+08,5.273811e+07,4.988679e+07,6.807009e+07,...,5.015035e+07,6.667330e+06,2.012112e+07,2.284153e+07,6.314109e+06,1.779483e+06,2.357864e+07,5.213153e+06,1.203960e+07,1.234998e+07

In [34]:
# Identificar y contar valores nulos por columna
valores_nulos_ventas_totales = ventas_totales.isnull().sum()
valores_nulos_ventas_totales

indice_tiempo                           0
ventas_precios_corrientes               0
ventas_precios_constantes               0
ventas_totales_canal_venta              0
salon_ventas                            6
canales_on_line                         0
ventas_totales_medio_pago               0
efectivo                                0
tarjetas_debito                         1
tarjetas_credito                        7
otros_medios                            1
ventas_totales_grupo_articulos          0
subtotal_ventas_alimentos_bebidas      10
bebidas                                 1
almacen                                 2
panaderia                               1
lacteos                                 1
carnes                                  1
verduleria_fruteria                     1
alimentos_preparados_rotiseria          1
articulos_limpieza_perfumeria           0
indumentaria_calzado_textiles_hogar     2
electronicos_articulos_hogar            3
otros                                   4
dtype: int64

In [35]:
#Realizamos una copia del dataframe
copia_ventas_totales=ventas_totales.copy()

In [36]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto
copia_ventas_totales["salon_ventas"]= copia_ventas_totales["salon_ventas"].fillna(0)
copia_ventas_totales["tarjetas_credito"]= copia_ventas_totales["tarjetas_credito"].fillna(0)
copia_ventas_totales["otros"]= copia_ventas_totales["otros"].fillna(0)
copia_ventas_totales["almacen"]= copia_ventas_totales["almacen"].fillna(0)
copia_ventas_totales["indumentaria_calzado_textiles_hogar"]= copia_ventas_totales["indumentaria_calzado_textiles_hogar"].fillna(0)
copia_ventas_totales["electronicos_articulos_hogar"]= copia_ventas_totales["electronicos_articulos_hogar"].fillna(0)

In [37]:
#Corroboramos valores nulos
valores_nulos=copia_ventas_totales.isnull().sum()
valores_nulos

indice_tiempo                           0
ventas_precios_corrientes               0
ventas_precios_constantes               0
ventas_totales_canal_venta              0
salon_ventas                            0
canales_on_line                         0
ventas_totales_medio_pago               0
efectivo                                0
tarjetas_debito                         1
tarjetas_credito                        0
otros_medios                            1
ventas_totales_grupo_articulos          0
subtotal_ventas_alimentos_bebidas      10
bebidas                                 1
almacen                                 0
panaderia                               1
lacteos                                 1
carnes                                  1
verduleria_fruteria                     1
alimentos_preparados_rotiseria          1
articulos_limpieza_perfumeria           0
indumentaria_calzado_textiles_hogar     0
electronicos_articulos_hogar            0
otros                                   0
dtype: int64

In [38]:
#Quinto método de sustitución de valores nulos
#Sustituir valores nulos por valores no nulos hacia adelante  "forward fill" ("ffill")
#Filtro por columnas
copia_ventas_totales["tarjetas_debito"] =copia_ventas_totales["tarjetas_debito"].fillna(method="ffill")
copia_ventas_totales["otros_medios"] =copia_ventas_totales["otros_medios"].fillna(method="ffill")
copia_ventas_totales["bebidas"] =copia_ventas_totales["bebidas"].fillna(method="ffill")
copia_ventas_totales["lacteos"] =copia_ventas_totales["lacteos"].fillna(method="ffill")
copia_ventas_totales["panaderia"] =copia_ventas_totales["panaderia"].fillna(method="ffill")
copia_ventas_totales["carnes"] =copia_ventas_totales["carnes"].fillna(method="ffill")
copia_ventas_totales["verduleria_fruteria"] =copia_ventas_totales["verduleria_fruteria"].fillna(method="ffill")
copia_ventas_totales["alimentos_preparados_rotiseria"] =copia_ventas_totales["alimentos_preparados_rotiseria"].fillna(method="ffill")

<ipython-input-38-a4e53e5e1513>:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  copia_ventas_totales["tarjetas_debito"] =copia_ventas_totales["tarjetas_debito"].fillna(method="ffill")
<ipython-input-38-a4e53e5e1513>:5: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  copia_ventas_totales["otros_medios"] =copia_ventas_totales["otros_medios"].fillna(method="ffill")
<ipython-input-38-a4e53e5e1513>:6: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  copia_ventas_totales["bebidas"] =copia_ventas_totales["bebidas"].fillna(method="ffill")
<ipython-input-38-a4e53e5e1513>:7: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  copia_ventas_totales["lacteos"] =copia_ventas_totales["lacteos"].fillna(method="ffill")
<ipython-input-38-a4e53e5e1513>:8: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  copia_ventas_totales["panaderia"] =copia_ventas_totales["panaderia"].fillna(method="ffill")
<ipython-input-38-a4e53e5e1513>:9: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  copia_ventas_totales["carnes"] =copia_ventas_totales["carnes"].fillna(method="ffill")
<ipython-input-38-a4e53e5e1513>:10: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  copia_ventas_totales["verduleria_fruteria"] =copia_ventas_totales["verduleria_fruteria"].fillna(method="ffill")
<ipython-input-38-a4e53e5e1513>:11: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  copia_ventas_totales["alimentos_preparados_rotiseria"] =copia_ventas_totales["alimentos_preparados_rotiseria"].fillna(method="ffill")

In [39]:
#Corroboramos valores nulos
valores_nulos=copia_ventas_totales.isnull().sum()
valores_nulos

indice_tiempo                           0
ventas_precios_corrientes               0
ventas_precios_constantes               0
ventas_totales_canal_venta              0
salon_ventas                            0
canales_on_line                         0
ventas_totales_medio_pago               0
efectivo                                0
tarjetas_debito                         0
tarjetas_credito                        0
otros_medios                            0
ventas_totales_grupo_articulos          0
subtotal_ventas_alimentos_bebidas      10
bebidas                                 0
almacen                                 0
panaderia                               0
lacteos                                 0
carnes                                  0
verduleria_fruteria                     0
alimentos_preparados_rotiseria          0
articulos_limpieza_perfumeria           0
indumentaria_calzado_textiles_hogar     0
electronicos_articulos_hogar            0
otros                                   0
dtype: int64

In [40]:
#Segundo método de sustitución de valores nulos
#Sustituir valores nulos con mediana
copia_ventas_totales["subtotal_ventas_alimentos_bebidas"]=copia_ventas_totales["subtotal_ventas_alimentos_bebidas"].fillna(round(copia_ventas_totales["subtotal_ventas_alimentos_bebidas"].median(),1))

In [41]:
#Corroboramos valores nulos
valores_nulos=copia_ventas_totales.isnull().sum()
valores_nulos

indice_tiempo                          0
ventas_precios_corrientes              0
ventas_precios_constantes              0
ventas_totales_canal_venta             0
salon_ventas                           0
canales_on_line                        0
ventas_totales_medio_pago              0
efectivo                               0
tarjetas_debito                        0
tarjetas_credito                       0
otros_medios                           0
ventas_totales_grupo_articulos         0
subtotal_ventas_alimentos_bebidas      0
bebidas                                0
almacen                                0
panaderia                              0
lacteos                                0
carnes                                 0
verduleria_fruteria                    0
alimentos_preparados_rotiseria         0
articulos_limpieza_perfumeria          0
indumentaria_calzado_textiles_hogar    0
electronicos_articulos_hogar           0
otros                                  0
dtype: int64

In [42]:
#Convertir archivo filtrado a CSV
copia_ventas_totales.to_csv("Ventas Totales.csv")

In [43]:
#Descargar archivo en csv
from google.colab import files
files.download("Ventas Totales.csv")