In [24]:
#Importar librerias necesarias
import pandas as pd

In [25]:
#Carga desde un archivo .csv sin indice y eliminar filas innecesarias
gastos_costos_20=pd.read_excel("Gastos y costos 20-23.xlsx",sheet_name="2020", skiprows=5)
gastos_costos_20

,FECHA,FOLIO,UUID,RFC,PROVEEDOR,TIPO GASTO,GASTO,DESCRIPCION,TC,IMPORTE,IVA,RET ISR,RET IVA,TOTAL MX,TOTAL SAT,TIPO,STATUS,POLIZA,Columna1
0,2020-01-01,39408,BD20F436-72CC-4BE2-AD37-5999D71AA391,ARE080115PBA,ARSI RENTA SA DE CV,MAQUINARIA,NaN,"Descripción: REVOLVEDORA, Modelo: ULTRAMP9A, M...",1.0,0.00,2248.28,0.0,0.0,2248.28,16300.00,I,Vigente,NaN,14051.72
1,2020-01-01,0001010100750847116902,85AEAC2E-6395-44A0-9CB9-754D06893375,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,NaN,COMISION COBRADA,1.0,490.00,78.40,0.0,0.0,568.40,568.40,I,Vigente,NaN,0.00
2,2020-01-01,0001010100752163714102,BD0DFE85-D776-41CB-9C5C-4FA7923E687A,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,NaN,COMISION COBRADA,1.0,195.00,31.20,0.0,0.0,226.20,226.20,I,Vigente,NaN,0.00
3,2020-01-01,3663,EF4504D6-830D-415C-AF03-80CF54C5E28E,PSS120625C86,PROMOTORA DE SERVICIOS Y SOLUCIONES EMPRESARIA...,HONORARIOS CONTABLES,NaN,HONORARIOS CONTABLES\nDEL MES DE ENERO DEL 2020.,1.0,10694.25,1711.08,0.0,0.0,12405.33,12405.33,I,Vigente,NaN,0.00
4,2020-01-01,2849,EC2F4AA4-BA64-4E2E-A5B7-4EBBE042D6D3,ENA7006081P0,ELECTROTERMICA NACIONAL SA DE CV,COMPRAS,NaN,Pago,1.0,0.00,NaN,0.0,0.0,0.00,0.00,P,Vigente,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3337,2020-12-01,125834,80BCB1D8-673F-495B-9C2A-4AC9F9CB38E5,SQS110113MU0,SERVICIO QUINTANA SUR S.A DE C.V,COMBUSTIBLE,G VTA,32011 MAGNA,1.0,129.79,20.21,0.0,0.0,150.00,150.00,I,Vigente,NaN,0.00
3338,2020-12-01,37652,D4C7C1FB-03A7-4046-A2BD-03EBE7DA861E,PSQ790724C90,"CIA. PERIODISTICA DEL SOL DE QUERETARO, S.A. D...",PUBLICIDAD,G VTA,82101504-PUBLICIDAD EN PERIODICOSCALOR Y CONTROL,1.0,2284.80,365.57,0.0,0.0,2650.37,2650.37,I,Vigente,NaN,0.00
3339,2020-12-01,160,FFCEE7D4-1F38-4D44-BE02-EB042DAACEE7,SQX981027RY5,"SUPER Q, S. A. DE C. V.",ALIMENTOS,G VTA,REF VICTORIA GROSELLA 3 LT PET NR,1.0,163.79,26.21,0.0,0.0,190.00,190.00,I,Vigente,NaN,0.00
3340,2020-12-01,634875,8DFF4F01-2F8B-4085-B116-05A314108B02,BIN940223KE0,"BANCO INVEX, S.A., INSTITUCION DE BANCA MULTIP...",COMISION BANCARIA,G FINA,COMISIONES E INTERESES,1.0,0.00,0.00,0.0,0.0,0.00,0.00,I,Vigente,NaN,0.00
3341,2020-12-01,1044477,F18225D6-4024-4F03-A15A-D18917386D59,EFE8908015L3,EFECTIVALE S. de R.L. de C.V.,COMBUSTIBLE,G VTA,CONSUMOS DE COMBUSTIBLE DE MONEDEROS ELECTRONICOS,1.0,14889.29,0.00,0.0,0.0,14889.29,14889.29,I,Vigente,NaN,0.00

In [26]:
#Identificar valores nulos por columna
valores_nulos_gastos_costos_20=gastos_costos_20.isnull().sum()
valores_nulos_gastos_costos_20

FECHA             0
FOLIO           189
UUID              0
RFC               0
PROVEEDOR         0
TIPO GASTO        0
GASTO          2502
DESCRIPCION       0
TC              391
IMPORTE          34
IVA             268
RET ISR           0
RET IVA           0
TOTAL MX          0
TOTAL SAT         0
TIPO              1
STATUS            0
POLIZA         3321
Columna1          0
dtype: int64

In [27]:
#Realizamos una copia del dataframe
copia_gastos_costos_20= gastos_costos_20.copy()

In [28]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto
copia_gastos_costos_20["FOLIO"]=copia_gastos_costos_20["FOLIO"].fillna("F0000")
copia_gastos_costos_20["GASTO"]=copia_gastos_costos_20["GASTO"].fillna("INDEFINIDO")
copia_gastos_costos_20["POLIZA"]=copia_gastos_costos_20["POLIZA"].fillna("SIN POLIZA")
copia_gastos_costos_20["TIPO"]=copia_gastos_costos_20["TIPO"].fillna("INFO FALTANTE")

In [29]:
#Corroboramos valores nulos
valores_nulos=copia_gastos_costos_20.isnull().sum()
valores_nulos

FECHA            0
FOLIO            0
UUID             0
RFC              0
PROVEEDOR        0
TIPO GASTO       0
GASTO            0
DESCRIPCION      0
TC             391
IMPORTE         34
IVA            268
RET ISR          0
RET IVA          0
TOTAL MX         0
TOTAL SAT        0
TIPO             0
STATUS           0
POLIZA           0
Columna1         0
dtype: int64

In [30]:
#Quinto método de sustitución de valores nulos
#Sustituir valores nulos por valores no nulos hacia adelante  "forward fill" ("ffill")
#Filtro por columnas
copia_gastos_costos_20["TC"]=copia_gastos_costos_20["TC"].fillna(method="ffill")

<ipython-input-30-c746d70cb4c9>:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  copia_gastos_costos_20["TC"]=copia_gastos_costos_20["TC"].fillna(method="ffill")

In [31]:
#Corroboramos valores nulos
valores_nulos=copia_gastos_costos_20.isnull().sum()
valores_nulos

FECHA            0
FOLIO            0
UUID             0
RFC              0
PROVEEDOR        0
TIPO GASTO       0
GASTO            0
DESCRIPCION      0
TC               0
IMPORTE         34
IVA            268
RET ISR          0
RET IVA          0
TOTAL MX         0
TOTAL SAT        0
TIPO             0
STATUS           0
POLIZA           0
Columna1         0
dtype: int64

In [32]:
#Primer método de sustitución de valores nulos
#Sustituir valores nulos con promedio o media
copia_gastos_costos_20["IMPORTE"]=copia_gastos_costos_20["IMPORTE"].fillna(round(copia_gastos_costos_20['IMPORTE'].mean(),1))
copia_gastos_costos_20["IVA"]=copia_gastos_costos_20["IVA"].fillna(round(copia_gastos_costos_20['IVA'].mean(),1))

In [33]:
#Corroboramos valores nulos
valores_nulos=copia_gastos_costos_20.isnull().sum()
valores_nulos

FECHA          0
FOLIO          0
UUID           0
RFC            0
PROVEEDOR      0
TIPO GASTO     0
GASTO          0
DESCRIPCION    0
TC             0
IMPORTE        0
IVA            0
RET ISR        0
RET IVA        0
TOTAL MX       0
TOTAL SAT      0
TIPO           0
STATUS         0
POLIZA         0
Columna1       0
dtype: int64

In [34]:
#Convertir archivo filtrado a CSV
copia_gastos_costos_20.to_csv("gastos_costos_20.csv")

In [35]:
#Descargar archivo en csv
from google.colab import files
files.download("gastos_costos_20.csv")