In [1]:
#Importar librerias necesarias
import pandas as pd

In [18]:
#Carga desde un archivo .csv sin indice y eliminar filas innecesarias
gastos_costos_23=pd.read_excel("Gastos y costos 20-23.xlsx",sheet_name="2023",skiprows=3)
gastos_costos_23

,Fecha,Folio,UUID,RFC,Proveedor,TIPO GASTO,Descripción,MP,FP,TC,Importe,IVA,RET ISR,RET IVA,Otros,TOTAL MX,TOTAL SAT,Tipo,Status,Poliza
0,2023-01-01,31,49536321-60A4-523E-A32F-E8BDF5C2276E,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,NaN,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN
1,2023-01-01,38,20FBB63B-D550-512F-9668-EEC6F983CEB7,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,NaN,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN
2,2023-01-01,341932,DB8C4388-D4E0-4F0C-A09C-77C773257F44,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006876 30/36 de 03/12/...,PPD,99.0,1.0,5551.38,888.22,0.0,0.0,NaN,6439.60,6439.60,I,Vigente,PE01-ENE23
3,2023-01-01,341933,A81A63F5-D5EC-4601-803E-375AF9CC5021,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006877 30/36 de 03/12/...,PPD,99.0,1.0,5551.98,888.32,0.0,0.0,NaN,6440.30,6440.30,I,Vigente,PE02-ENE23
4,2023-01-01,342205,DCC10492-DE51-4C87-8430-5676FBF81931,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000009486 5/48 de 03/12/2...,PPD,99.0,1.0,8454.37,1352.70,0.0,0.0,NaN,9807.07,9807.07,I,Vigente,PE03-ENE23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,2023-02-01,882974,3E97C399-6747-4BCA-8436-ED4B0933DF33,BIN940223KE0,"BANCO INVEX, S.A., INSTITUCION DE BANCA MULTIP...",COMISION BANCARIA,COMISIONES E INTERESES,PUE,3.0,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,I,Vigente,NaN
393,2023-02-01,053560,B7132758-F800-4797-B1D6-CC61AFFEE444,BPU7901018D4,BEBIDAS PURIFICADAS,ALIMENTOS,Epura 20 Lts Policarbonato,PUE,1.0,1.0,220.00,0.00,0.0,0.0,NaN,220.00,220.00,I,Vigente,NaN
394,2023-02-01,1092957089,D1E2DC1E-9FFB-46C6-82E4-B350B83CB6F7,BMN930209927,BANCO MERCANTIL DEL NORTE SA INSTITUCION DE BA...,COMISION BANCARIA,SERVICIOS BANCARIOS,PUE,3.0,1.0,18071.52,682.40,0.0,0.0,NaN,18753.92,18753.92,I,Vigente,NaN
395,2023-02-01,1453820,6249FE27-6FA6-4EFB-910E-3CD67A0E29A1,EFE8908015L3,EFECTIVALE S. de R.L. de C.V.,GASOLINA,CONSUMOS DE COMBUSTIBLE DE MONEDEROS ELECTRONICOS,PUE,5.0,1.0,14472.32,0.00,0.0,0.0,NaN,14472.32,14472.32,I,Vigente,NaN
396,2023-02-01,18,439A9230-277E-5563-818C-7630B0E8D706,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,NaN,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN

In [19]:
#Identificar valores nulos por columna
valores_nulos_gastos_costos_23=gastos_costos_23.isnull().sum()
valores_nulos_gastos_costos_23

Fecha            0
Folio           13
UUID             0
RFC              0
Proveedor        0
TIPO GASTO       8
Descripción      0
MP              71
FP              71
TC               0
Importe          0
IVA              0
RET ISR          0
RET IVA          0
Otros          397
TOTAL MX         0
TOTAL SAT        0
Tipo             0
Status           0
Poliza         115
dtype: int64

In [20]:
#Realizamos una copia del dataframe
copia_gastos_costos_23 = gastos_costos_23.copy()

In [25]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto
copia_gastos_costos_23["Folio"]=copia_gastos_costos_23["Folio"].fillna("F0000")
copia_gastos_costos_23["TIPO GASTO"]=copia_gastos_costos_23["TIPO GASTO"].fillna("INFO FALTANTE")
copia_gastos_costos_23["Poliza"]=copia_gastos_costos_23["Poliza"].fillna("Sin Poliza")
copia_gastos_costos_23["MP"]=copia_gastos_costos_23["MP"].fillna("SIN REGISTRO")

In [26]:
#Corroboramos valores nulos
valores_nulos=copia_gastos_costos_23.isnull().sum()
valores_nulos

Fecha            0
Folio            0
UUID             0
RFC              0
Proveedor        0
TIPO GASTO       0
Descripción      0
MP               0
FP              71
TC               0
Importe          0
IVA              0
RET ISR          0
RET IVA          0
Otros          397
TOTAL MX         0
TOTAL SAT        0
Tipo             0
Status           0
Poliza           0
dtype: int64

In [27]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto
copia_gastos_costos_23["Otros"]=copia_gastos_costos_23["Otros"].fillna("0")

In [28]:
#Corroboramos valores nulos
valores_nulos=copia_gastos_costos_23.isnull().sum()
valores_nulos

Fecha           0
Folio           0
UUID            0
RFC             0
Proveedor       0
TIPO GASTO      0
Descripción     0
MP              0
FP             71
TC              0
Importe         0
IVA             0
RET ISR         0
RET IVA         0
Otros           0
TOTAL MX        0
TOTAL SAT       0
Tipo            0
Status          0
Poliza          0
dtype: int64

In [30]:
#Primer método de sustitución de valores nulos
#Sustituir valores nulos con promedio o media
copia_gastos_costos_23["FP"]=copia_gastos_costos_23["FP"].fillna(round(copia_gastos_costos_23['FP'].mean(),1))

In [31]:
#Corroboramos valores nulos
valores_nulos=copia_gastos_costos_23.isnull().sum()
valores_nulos

Fecha          0
Folio          0
UUID           0
RFC            0
Proveedor      0
TIPO GASTO     0
Descripción    0
MP             0
FP             0
TC             0
Importe        0
IVA            0
RET ISR        0
RET IVA        0
Otros          0
TOTAL MX       0
TOTAL SAT      0
Tipo           0
Status         0
Poliza         0
dtype: int64

In [32]:
#Convertir archivo filtrado a CSV
copia_gastos_costos_23.to_csv("gastos_costos_23.csv")

In [33]:
#Descargar archivo en csv
from google.colab import files
files.download("gastos_costos_23.csv")