In [1]:
#Importar librerias necesarias
import pandas as pd

In [2]:
#Carga desde un archivo .csv sin indice y eliminar filas innecesarias
gastos_costos_22=pd.read_excel("Gastos y costos 20-23.xlsx",sheet_name="2022", skiprows=3)
gastos_costos_22

,Fecha,Folio,UUID,RFC,Proveedor,TIPO GASTO,Descripción,MP,TC,Importe,IVA,RET ISR,RET IVA,Otros,TOTAL MX,TOTAL SAT,Tipo,Status,Poliza
0,2022-01-01,280108,9DA0E63F-1D47-441F-93D7-C2E05AE4D35E,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006876 18/36 de 03/12/...,PPD,1.0,5551.38,888.22,0.0,0.0,NaN,6439.60,6439.60,I,Vigente,PE02-ENE22
1,2022-01-01,280109,7E00E776-A839-4D57-B291-411109164B2F,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006877 18/36 de 03/12/...,PPD,1.0,5551.98,888.32,0.0,0.0,NaN,6440.30,6440.30,I,Vigente,PE03-ENE22
2,2022-01-01,007817297284,BB6585C1-3B54-4130-AFD0-1867C3764821,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,Servicios de Facturación,PUE,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,I,Vigente,NaN
3,2022-01-01,5595,B5E4B4EB-6C2F-11EC-BB9D-00155D014009,ZEGC530520V4A,CARLOS ENRIQUE ZERMEÑO GUTIERREZ,COMPRAS,Pago,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN
4,2022-01-01,5614,BB6756D1-6CCD-11EC-947D-00155D014407,ZEGC530520V4A,CARLOS ENRIQUE ZERMEÑO GUTIERREZ,COMPRAS,Pago,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2572,2022-12-01,863376,E90DA089-3C3B-45C8-A19C-B8810D222F60,BIN940223KE0,"BANCO INVEX, S.A., INSTITUCION DE BANCA MULTIP...",COMISION BANCARIA,COMISIONES E INTERESES,PUE,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,I,Vigente,NaN
2573,2022-12-01,1092957089,D720ED7C-F370-4236-B269-8873ABB78745,BMN930209927,BANCO MERCANTIL DEL NORTE SA INSTITUCION DE BA...,COMISION BANCARIA,SERVICIOS BANCARIOS,PUE,1.0,17310.30,516.32,0.0,0.0,NaN,17826.62,17826.62,I,Vigente,NaN
2574,2022-12-01,4,0AFD3EB5-F3DD-43EB-B9FA-79D793CFF417,AAE6411055P8,Aesa Articulos Electricos S.A de C.V,COMPRAS,Pago,NaN,NaN,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN
2575,2022-12-01,16,E3CA1DA8-581A-5844-80D2-CF0317B3BBEA,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,NaN,NaN,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN
2576,2022-12-01,17,17178BA2-9CCE-54F8-A4B8-3E5F98D4DB8E,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,NaN,NaN,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN

In [9]:
#Identificar valores nulos por columna
valores_nulos_gastos_costos_22=gastos_costos_22.isnull().sum()
valores_nulos_gastos_costos_22

Fecha             0
Folio           102
UUID              0
RFC               0
Proveedor         0
TIPO GASTO        0
Descripción       0
MP              553
TC              636
Importe           0
IVA               0
RET ISR           0
RET IVA           0
Otros          2577
TOTAL MX          0
TOTAL SAT         0
Tipo              0
Status            0
Poliza          801
dtype: int64

In [10]:
#Realizamos una copia del dataframe
copia_gastos_costos_22= gastos_costos_22.copy()

In [11]:
#Primer método de sustitución de valores nulos
#Sustituir valores nulos con promedio o media
copia_gastos_costos_22["TC"]=copia_gastos_costos_22["TC"].fillna(round(copia_gastos_costos_22["TC"].mean(),1))

In [12]:
#Corroboramos valores nulos
valores_nulos=copia_gastos_costos_22.isnull().sum()
valores_nulos

Fecha             0
Folio           102
UUID              0
RFC               0
Proveedor         0
TIPO GASTO        0
Descripción       0
MP              553
TC                0
Importe           0
IVA               0
RET ISR           0
RET IVA           0
Otros          2577
TOTAL MX          0
TOTAL SAT         0
Tipo              0
Status            0
Poliza          801
dtype: int64

In [13]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto
copia_gastos_costos_22["Folio"] = copia_gastos_costos_22["Folio"].fillna("F0000")
copia_gastos_costos_22["Otros"] = copia_gastos_costos_22["Otros"].fillna("N/A")
copia_gastos_costos_22["Poliza"] = copia_gastos_costos_22["Poliza"].fillna("N/A")

In [14]:
#Corroboramos valores nulos
valores_nulos=copia_gastos_costos_22.isnull().sum()
valores_nulos

Fecha            0
Folio            0
UUID             0
RFC              0
Proveedor        0
TIPO GASTO       0
Descripción      0
MP             553
TC               0
Importe          0
IVA              0
RET ISR          0
RET IVA          0
Otros            0
TOTAL MX         0
TOTAL SAT        0
Tipo             0
Status           0
Poliza           0
dtype: int64

In [21]:
#Sexto método de sustitución de valores nulos
#Sustituir valores nulos por valores no nulos hacia adelante con "forward fill" ("ffill")
copia_gastos_costos_22["MP"] = copia_gastos_costos_22["MP"].fillna(method="ffill")

<ipython-input-21-9cf3fe7a02dd>:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  copia_gastos_costos_22["MP"] = copia_gastos_costos_22["MP"].fillna(method="ffill")

In [22]:
#Corroboramos valores nulos
valores_nulos=copia_gastos_costos_22.isnull().sum()
valores_nulos

Fecha          0
Folio          0
UUID           0
RFC            0
Proveedor      0
TIPO GASTO     0
Descripción    0
MP             0
TC             0
Importe        0
IVA            0
RET ISR        0
RET IVA        0
Otros          0
TOTAL MX       0
TOTAL SAT      0
Tipo           0
Status         0
Poliza         0
dtype: int64

In [23]:
#Convertir archivo filtrado a CSV
copia_gastos_costos_22.to_csv("gastos_costos_22.csv")

In [24]:
#Descargar archivo en csv
from google.colab import files
files.download("gastos_costos_22.csv")