In [1]:
#Importar librerias necesarias
import pandas as pd

In [2]:
#Carga desde un archivo .csv sin indice
detalle_pyp=pd.read_excel("Detalle precios y productos fabricados 2022.xlsx")
detalle_pyp

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1.0,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1.0,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7.0,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1.0,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2.0,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1421,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6.0,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
1422,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6.0,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3.0,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1.0,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10.0,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

In [3]:
#Identificar valores nulos por columna
valores_nulos_detalle_pyp=detalle_pyp.isnull().sum()
valores_nulos_detalle_pyp

CVE_DOC                      3
FECHA_DOC                    3
NOMBRE_VENDEDOR              2
NOMBRE_CLIENTE               2
CANT                         7
CVE_ART                      2
DESCR                        2
PRECIO_UNITARIO              2
COSTO_UNITARIO               4
COSTO_UNITARIO_CALCULADO     2
SUBTOTAL_PARTIDA             4
COSTO_TOTAL_CALCULADO        0
MARGEN_UNITARIO_CALCULADO    0
MARGEN_TOTAL_CALCULADO       0
dtype: int64

In [26]:
#Realizamos una copia del dataframe
copia_detalle=detalle_pyp.copy()

In [27]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto
copia_detalle["CVE_DOC"] = copia_detalle["CVE_DOC"].fillna("F0000")
copia_detalle["NOMBRE_VENDEDOR"]=copia_detalle["NOMBRE_VENDEDOR"].fillna("VENDEDOR X")
copia_detalle["NOMBRE_CLIENTE"]=copia_detalle["NOMBRE_CLIENTE"].fillna("CLIENTE X")
copia_detalle["DESCR"]=copia_detalle["DESCR"].fillna("SIN DESCRIPCION")
copia_detalle["CVE_ART"]=copia_detalle["CVE_ART"].fillna("F000")
copia_detalle["FECHA_DOC"]=copia_detalle["FECHA_DOC"].fillna("XXXX-XX-XX")

In [28]:
#Corroboramos valores nulos
valores_nulos=copia_detalle.isnull().sum()
valores_nulos

CVE_DOC                      0
FECHA_DOC                    0
NOMBRE_VENDEDOR              0
NOMBRE_CLIENTE               0
CANT                         7
CVE_ART                      0
DESCR                        0
PRECIO_UNITARIO              2
COSTO_UNITARIO               4
COSTO_UNITARIO_CALCULADO     2
SUBTOTAL_PARTIDA             4
COSTO_TOTAL_CALCULADO        0
MARGEN_UNITARIO_CALCULADO    0
MARGEN_TOTAL_CALCULADO       0
dtype: int64

In [24]:
#Primer método de sustitución de valores nulos
#Sustituir valores nulos con promedio o media
copia_detalle["CANT"]=copia_detalle["CANT"].fillna(round(copia_detalle["CANT"].mean(),1))
copia_detalle["PRECIO_UNITARIO"]=copia_detalle["PRECIO_UNITARIO"].fillna(round(copia_detalle["PRECIO_UNITARIO"].mean(),1))
copia_detalle["SUBTOTAL_PARTIDA"]=copia_detalle["SUBTOTAL_PARTIDA"].fillna(round(copia_detalle["SUBTOTAL_PARTIDA"].mean(),1))
copia_detalle["COSTO_UNITARIO"]=copia_detalle["COSTO_UNITARIO"].fillna(round(copia_detalle["COSTO_UNITARIO"].mean(),1))
copia_detalle["COSTO_UNITARIO_CALCULADO"]=copia_detalle["COSTO_UNITARIO_CALCULADO"].fillna(round(copia_detalle["COSTO_UNITARIO_CALCULADO"].mean(),1))

In [25]:
#Corroboramos valores nulos
valores_nulos=copia_detalle.isnull().sum()
valores_nulos

CVE_DOC                      0
FECHA_DOC                    0
NOMBRE_VENDEDOR              0
NOMBRE_CLIENTE               0
CANT                         0
CVE_ART                      0
DESCR                        0
PRECIO_UNITARIO              0
COSTO_UNITARIO               0
COSTO_UNITARIO_CALCULADO     0
SUBTOTAL_PARTIDA             0
COSTO_TOTAL_CALCULADO        0
MARGEN_UNITARIO_CALCULADO    0
MARGEN_TOTAL_CALCULADO       0
dtype: int64

In [29]:
#Convertir archivo filtrado a CSV
copia_detalle.to_csv("Detalle_precios_yp_roductos.csv")

In [30]:
#Descargar archivo en csv
from google.colab import files
files.download("Detalle_precios_yp_roductos.csv")